# Generated by Django 2.0.3 on 2018-08-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='product.Collection')),
            ],
            options={
                'permissions': (('view', 'Can view popular collections'), ('edit', 'Can edit popular collections')),
            },
        ),
    ]
